// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaigonRide.Data;

#nullable disable

namespace SaigonRide.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430110813_InitialDBWithSeeds")]
    partial class InitialDBWithSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaigonRide.Models.entities.RentalTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDiscountApplied")
                        .HasColumnType("bit");

                    b.Property<int>("ReturnStationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalDue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReturnStationId");

                    b.HasIndex("VehicleId");

                    b.ToTable("RentalTransactions");
                });

            modelBuilder.Entity("SaigonRide.Models.entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentInventory")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentInventory = 42,
                            LocationName = "District 1, HCM",
                            MaxCapacity = 50
                        },
                        new
                        {
                            Id = 3,
                            CurrentInventory = 3,
                            LocationName = "Binh Thanh, HCM",
                            MaxCapacity = 20
                        });
                });

            modelBuilder.Entity("SaigonRide.Models.entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerMinute")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Standard Bike",
                            PricePerMinute = 500m,
                            StationId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "E-Scooter",
                            PricePerMinute = 1500m,
                            StationId = 1
                        });
                });

            modelBuilder.Entity("SaigonRide.Models.entities.RentalTransaction", b =>
                {
                    b.HasOne("SaigonRide.Models.entities.Station", "ReturnStation")
                        .WithMany()
                        .HasForeignKey("ReturnStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaigonRide.Models.entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReturnStation");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SaigonRide.Models.entities.Vehicle", b =>
                {
                    b.HasOne("SaigonRide.Models.entities.Station", "Station")
                        .WithMany("Vehicles")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("SaigonRide.Models.entities.Station", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
